x-airflow-common: &airflow-common
  image: apache/airflow:2.7.1-python3.10
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://web-redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@db:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
  networks:
    - sobi-net
  depends_on:
    - airflow-init

services:
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8089:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    image: apache/airflow:2.8.1
    restart: no
    depends_on:
      - db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com
      "

  mlflow:
    image: bitnami/mlflow:3.1.4-debian-12-r6
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://airflow:airflow@db:5432/mlflow
      --default-artifact-root /bitnami/mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlflow/mlruns:/bitnami/mlflow/artifacts
    networks:
      - sobi-net
    depends_on:
      - db

networks:
  sobi-net:
    external: true

