services:
  frontend-green:
    build: 
      context: ./frontend/my-app
      dockerfile: Dockerfile
    image: sobi/frontend:green
    container_name: sobi-frontend-green
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=https://13.125.215.242
      - NEXT_PUBLIC_FRONTEND_URL=https://13.125.215.242
    depends_on:
      - backend-green
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - sobi-net
  
  backend-green:
    build:
      context: ./backend/sobi_backend 
      dockerfile: ../Dockerfile        
    image: sobi/backend:green
    container_name: sobi-backend-green
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sobi
      - SPRING_DATASOURCE_USERNAME=sobiuser
      - SPRING_DATASOURCE_PASSWORD=sobipass
      - SPRING_DATA_REDIS_HOST=redis
      - APP_MQTT_BROKER_URL=tcp://172.26.6.236:1883
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - sobi-net

  db:
    image: postgres:15.4
    container_name: sobi-db
    environment:
      - POSTGRES_DB=sobi
      - POSTGRES_USER=sobiuser
      - POSTGRES_PASSWORD=sobipass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sobi-net

  redis:
    image: redis:7.2.1
    container_name: sobi-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - sobi-net

volumes:
  db_data:

networks:
  sobi-net:
    name: sobi-net
    driver: bridge