services:
  jenkins:
    environment:
        - TZ=Asia/Seoul
    build:
      context: ./infra
      dockerfile: Dockerfile
    user: root
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - ./nginx:/app/nginx # 호스트의 nginx 디렉토리를 컨테이너의 /app/nginx에 마운트
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - sobi-net
  
volumes:
  jenkins_home:

networks:
  sobi-net:
    external: true
