services:
  nginx:
    image: nginx:1.25.5-alpine
    container_name: sobi-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
  
  backend:
    build: ./backend
    image: sobi/backend:1.0
    container_name: sobi-backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sobi
      - SPRING_DATASOURCE_USERNAME=sobiuser
      - SPRING_DATASOURCE_PASSWORD=sobipass
      - REDIS_HOST=redis
      - MQTT_BROKER_URL=tcp://mqtt:1883
    depends_on:
      - db
      - redis
      - mqtt
  
  db:
    image: postgres:15.4
    container_name: sobi-db
    environment:
      - POSTGRES_DB=sobi
      - POSTGRES_USER=sobiuser
      - POSTGRES_PASSWORD=sobipass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1
    container_name: sobi-redis
    ports:
      - "6379:6379"
  
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: sobi-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config:ro
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

volumes:
  db_data:
