services:
  jenkins:
    environment:
        - TZ=Asia/Seoul
    build:
      context: ./infra
      dockerfile: Dockerfile
    user: root
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - sobi-net
  
volumes:
  jenkins_home:

networks:
  sobi-net:
    external: true
