global:
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: ${ALERT_SMTP_FROM}
  smtp_auth_username: ${ALERT_SMTP_USER}
  smtp_auth_password: ${ALERT_SMTP_PASS}
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: '${ALERT_SMTP_TO}'
        send_resolved: true
